### PR TITLE
[DOCS] Make it easier to find out the inline is now Collection

### PR DESCRIPTION
**Pull request by linawolf**

### CODE REVIEW

**Comment by nhovratov** [comment]
We have this overview for this: https://docs.typo3.org/p/friendsoftypo3/content-blocks/main/en-us/Appendix/TcaTypeMapping/Index.html

**Comment by linawolf** [comment]
When you rename concepts it cannot mention to put hints in several places. At least me I keep looking for it

**Comment by nhovratov** [comment]
Ok, but I wouldn't link a button `Inline` as this would imply a Content Blocks Field Type with such a name exists. We could better add a link to the table I mentioned.

Note: In terms of Content Blocks, TCA is an internal detail. That's why it is only added in the appendix and there is a small note in each FieldType at the top, which TCA type it represents. We don't want new users to bother with this concept. Content Blocks is targeted for newcomers and frontend developers first. Developers, which are familiar with TCA and stuff should look into the appendix. And if you are migrating to Content Blocks from plain TCA, then you are expected to know, what you are doing.

**Comment by linawolf** [comment]
Ok, maybe find another solution

**Pull request closed without merging**
