### PR TITLE
Fix missing _raw for relations to none content block tables

### LINKED ISSUE #134: TypeError from 0.5.0 -> 0.6.1 for type Select
Error raised:
```
(1/1) TypeError

Cannot assign null to property TYPO3\CMS\ContentBlocks\DataProcessing\ResolvedRelation::$raw of type array
```

by the following field config:

```yaml
    -
        identifier: 'customer'
        type: 'Select'
        renderType: 'selectMultipleSideBySide'
        foreign_table: 'sys_category'
        foreign_table_where: 'AND {#sys_category}.{#parent} = ###SITE:settings.parentPids.categoryCustomer###'
        minitems: 1
        maxitems: 1
        sortItems:
            label: 'asc'
        fieldControl:
            editPopup:
                disabled: false
            addRecord:
                disabled: false
                options:
                    table: 'sys_category'
                    pid: '###PAGE_TSCONFIG_ID###'
                    setValue: 'set'
```

Stack trace:

<details><summary>Details</summary>

```
in /vendor/contentblocks/content-blocks/Classes/DataProcessing/ContentBlockDataDecorator.php line 212

            unset($item['_table']);
        } else {
            $foreignTable = $this->getForeignTable($tcaFieldDefinition, $table);
        }
        $resolvedRelation->raw = $item['_raw'];
        unset($item['_raw']);
        $resolvedRelation->resolved = $item;
        $hasTableDefinition = $this->tableDefinitionCollection->hasTable($foreignTable);
        $collectionTableDefinition = null;

at TYPO3\CMS\ContentBlocks\DataProcessing\ContentBlockDataDecorator->transformSingleRelation()
in /vendor/contentblocks/content-blocks/Classes/DataProcessing/ContentBlockDataDecorator.php line 156

        ?PageLayoutContext $context = null,
    ): array|ContentBlockData {
        $renderType = $tcaFieldDefinition->getTca()['config']['renderType'] ?? '';
        if ($renderType === 'selectSingle') {
            $processedField = $this->transformSingleRelation(
                $processedField,
                $tcaFieldDefinition,
                $table,
                $depth,

at TYPO3\CMS\ContentBlocks\DataProcessing\ContentBlockDataDecorator->transformSelectRelation()
in /vendor/contentblocks/content-blocks/Classes/DataProcessing/ContentBlockDataDecorator.php line 118

                $table,
                $depth,
                $context,
            ),
            FieldType::SELECT => $this->transformSelectRelation(
                $resolvedField,
                $tcaFieldDefinition,
                $table,
                $depth,

at TYPO3\CMS\ContentBlocks\DataProcessing\ContentBlockDataDecorator->handleRelation()
in /vendor/contentblocks/content-blocks/Classes/DataProcessing/ContentBlockDataDecorator.php line 76

                continue;
            }
            $resolvedField = $resolvedRelation->resolved[$tcaFieldDefinition->getUniqueIdentifier()];
            if ($this->isRelationField($resolvedField, $tcaFieldDefinition, $table)) {
                $resolvedField = $this->handleRelation(
                    $resolvedRelation,
                    $tcaFieldDefinition,
                    $table,
                    $depth,

at TYPO3\CMS\ContentBlocks\DataProcessing\ContentBlockDataDecorator->buildContentBlockDataObjectRecursive()
in /vendor/contentblocks/content-blocks/Classes/DataProcessing/ContentBlockDataDecorator.php line 48

    ): ContentBlockData {
        $resolvedRelation = new ResolvedRelation();
        $resolvedRelation->raw = $rawData;
        $resolvedRelation->resolved = $resolvedData;
        $contentBlockData = $this->buildContentBlockDataObjectRecursive(
            $contentTypeDefinition,
            $tableDefinition,
            $resolvedRelation,
            $table,

at TYPO3\CMS\ContentBlocks\DataProcessing\ContentBlockDataDecorator->decorate()
in /vendor/contentblocks/content-blocks/Classes/DataProcessing/ContentBlocksDataProcessor.php line 51

            $tableDefinition,
            $processedData['data'],
            $table,
        );
        $processedData['data'] = $this->contentBlockDataDecorator->decorate(
            $contentTypeDefinition,
            $tableDefinition,
            $processedData['data'],
            $resolvedData,

at TYPO3\CMS\ContentBlocks\DataProcessing\ContentBlocksDataProcessor->process()
in /vendor/typo3/cms-frontend/Classes/ContentObject/ContentDataProcessor.php line 54

            foreach ($processorKeys as $key) {
                $dataProcessor = $this->dataProcessorRegistry->getDataProcessor($processors[$key])
                    ?? $this->getDataProcessor($processors[$key]);
                $processorConfiguration = $processors[$key . '.'] ?? [];
                $variables = $dataProcessor->process(
                    $cObject,
                    $configuration,
                    $processorConfiguration,
                    $variables

at TYPO3\CMS\Frontend\ContentObject\ContentDataProcessor->process()
in /vendor/typo3/cms-frontend/Classes/DataProcessing/DatabaseQueryProcessor.php line 91

            $recordContentObjectRenderer = GeneralUtility::makeInstance(ContentObjectRenderer::class);
            $recordContentObjectRenderer->setRequest($request);
            $recordContentObjectRenderer->start($record, $tableName);
            $processedRecordVariables[$key] = ['data' => $record];
            $processedRecordVariables[$key] = $this->contentDataProcessor->process($recordContentObjectRenderer, $processorConfiguration, $processedRecordVariables[$key]);
        }

        $processedData[$targetVariableName] = $processedRecordVariables;

at TYPO3\CMS\Frontend\DataProcessing\DatabaseQueryProcessor->process()
in /vendor/typo3/cms-frontend/Classes/ContentObject/ContentDataProcessor.php line 54

            foreach ($processorKeys as $key) {
                $dataProcessor = $this->dataProcessorRegistry->getDataProcessor($processors[$key])
                    ?? $this->getDataProcessor($processors[$key]);
                $processorConfiguration = $processors[$key . '.'] ?? [];
                $variables = $dataProcessor->process(
                    $cObject,
                    $configuration,
                    $processorConfiguration,
                    $variables

at TYPO3\CMS\Frontend\ContentObject\ContentDataProcessor->process()
in /vendor/typo3/cms-frontend/Classes/ContentObject/FluidTemplateContentObject.php line 82

        $this->setPartialRootPath($conf);
        $this->setExtbaseVariables($conf);
        $this->assignSettings($conf);
        $variables = $this->getContentObjectVariables($conf);
        $variables = $this->contentDataProcessor->process($this->cObj, $conf, $variables);

        $this->view->assignMultiple($variables);

        $this->renderFluidTemplateAssetsIntoPageRenderer($variables);
```

</details>

### PR DESCRIPTION
**Pull request by DanielSiepmann**
Content Block elements might have a relation to none content block tables, e.g. to sys_category.
Those were not properly enriched, leading to follow up issues.

The corresponding code is now extracted and always called.

Resolves: #134

### CODE REVIEW

**Comment by DanielSiepmann** [comment]
I still have the issue with this config:

```yaml
    -
        identifier: 'palette_meta'
        type: 'Palette'
        fields:
            -
                identifier: 'author'
                type: 'Select'
                renderType: 'selectSingle'
                foreign_table: 'be_users'
                foreign_table_where: 'be_users.{#lastlogin} > 0'
                minitems: 1
                items:
                    -
                        label: 'LLL:EXT:site_codappix/ContentBlocks/PageTypes/blogpost/Source/Language/Labels.xlf:author.default.label'
                        value: ''
```

Will post an update as soon as possible.
The original config from the issue is working fine with the patch.

**Comment by nhovratov** [comment]
I think there is a special case if renderType `selectSingle`.

**Comment by DanielSiepmann** [comment]
The issue is that there is not an array with records but a single record within https://github.com/nhovratov/content-blocks/blob/main/Classes/DataProcessing/RelationResolver.php#L157

I'll dig deeper :)

**Comment by DanielSiepmann** [comment]
```
diff --git a/Classes/DataProcessing/ContentBlockDataDecorator.php b/Classes/DataProcessing/ContentBlockDataDecorator.php
index b766c33..5c7e42c 100644
--- a/Classes/DataProcessing/ContentBlockDataDecorator.php
+++ b/Classes/DataProcessing/ContentBlockDataDecorator.php
@@ -153,6 +153,7 @@ final class ContentBlockDataDecorator
     ): array|ContentBlockData {
         $renderType = $tcaFieldDefinition->getTca()['config']['renderType'] ?? '';
         if ($renderType === 'selectSingle') {
+            $processedField = $processedField[0];
             $processedField = $this->transformSingleRelation(
                 $processedField,
                 $tcaFieldDefinition,
```

Solves the issue, but not sure if that's a proper fix.

**Comment by nhovratov** [comment]
Will have a look, thanks for the hint so far! I can take over from here.

**Pull request merged**
