### PR TITLE
[FEATURE] Add nonce attribute for CSP to css and script viewhelpers

### PR DESCRIPTION
**Pull request by peterkraume**
This patch introduces the nonce attribute (which is also used in the TYPO3 core) to content blocks. The nonce attribute is important for the Content Security Policy.

Also updated are:
- Code Generator
- Documentation
- Tests

### CODE REVIEW

**Comment by Bufallo** [comment]
Why would you want to add the nonce attribute when including files? Isn't that only needed for inline CSS/JS? If you include files a style/script-src: 'self' in CSP should be enough right?

**Comment by peterkraume** [comment]
I'm not that deep into CSP but the CSS and JS files added via TypoScript always get the nonce attribute when included:
```
<link rel="stylesheet" href="/typo3temp/assets/css/7015c8c4ac5ff815b57530b221005fc6.css?1702503841" media="all" nonce="nMrFO8SyhTYZdPqdD-z7jEsRpFTPZrW7UHZpeYCAcN1WgRRuftOMcA">
<link rel="stylesheet" href="/_assets/74080115b7823d36521aa0fac3aaa14b/Css/custom.css?1703974061" media="all" nonce="nMrFO8SyhTYZdPqdD-z7jEsRpFTPZrW7UHZpeYCAcN1WgRRuftOMcA">
```

Additionally the core viewhelpers include this behaviour and it makes sense to keep content blocks in line with them:
https://github.com/TYPO3/typo3/blob/570d83b66ba81a1d18ee0ab9abcacbf27d738d5a/typo3/sysext/fluid/Classes/ViewHelpers/Asset/CssViewHelper.php#L102

**Comment by Bufallo** [comment]
I think its a good thing to add the argument to the viewHelper to be consistent with the Core ViewHelpers. But its disabled as default. So i wouldnt activate it by default in the generated code.

**Comment by jonaseberle** [comment]
Ref: https://review.typo3.org/c/Packages/TYPO3.CMS/+/79166

**Comment by peterkraume** [comment]
I have removed the `nonce` attribute from the code generator.

**Comment by nhovratov** [comment]
Thanks!

**Pull request merged**
